### ISSUE TITLE
json-rpc ask from other code

### ISSUE THREAD

**Issue by romablog** [pocesar/node-jsonrpc2#23]
how to create request to rpc.server form code on AngularJS?
Is it possible or i should use only rpc.client for reqests?

**Comment by pocesar** [comment]
this module is focused on node.js side only. it can't be used on the browser. 

if angular has any module that can craft RPC requests, then it would work. 
just remember to set the CORS correctly, since the RPC server is usually listening on another port or another domain, unless you're using some sort of load balancer like nginx for internal proxy pass.
